#!/bin/bash

delete_m() {
  local size_with_unit=$1
  echo "${size_with_unit%M}"
}

previous_size=$(monitor_wal_size | awk '{print $1}')
previous_size=$(delete_m $previous_size)

while true
do
  current_size=$(monitor_wal_size | awk '{print $1}')
  current_size=$(delete_m $current_size)
  difference=$((current_size - previous_size))
  echo -ne "\r Speed: ${difference}M/s"
  previous_size=$current_size
  
  sleep 1
done