#!/bin/bash

if tmux has-session -t replication 2>/dev/null; then
    tmux attach-session -t replication
    exit 0
fi

tmux new-session -d -s replication

tmux split-window -v
tmux select-pane -t 0
tmux split-window -h
tmux split-window -h

tmux select-pane -t 0
tmux send-keys 'watch -n 0.5 monitor_replication' C-m

tmux select-pane -t 1
tmux send-keys 'watch -n 0.5 monitor_slots' C-m

tmux select-pane -t 2
tmux send-keys 'watch -n 0.5 "psql postgres -x -c \"select pg_current_wal_lsn(),pg_current_wal_insert_lsn(); \" "' C-m

tmux select-pane -t 3
tmux send-keys "watch -n 0.5 monitor_ps" C-m

tmux select-pane -t 3
tmux resize-pane -D 7

tmux attach-session -t replication
